version: '3'
services:
  todotests:
    build: ./todo-app/tests
    depends_on:
     - todofront
     - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - trybe-network-docker

  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - trybe-network-docker

  todoback: 
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    networks:
      - trybe-network-docker

networks:
  trybe-network-docker: